Disable dorny test-reporter, when running with ACT
dorny test-reporter tries to contact the GitHub REST API to create pages
to show the test reports. That's not going to work locally.

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -63,9 +63,10 @@ jobs:
 
     - name: Solidity Tests
       run: npm run test:solidity
+
     - name: Solidity Test Report
       uses: dorny/test-reporter@v1
-      if: success() || failure()              # run this step even if previous step failed
+      if: ${{ !env.ACT }} && (success() || failure())              # run this step even if previous step failed
       with:
         name: Solidity Tests                  # Name of the check run which will be created
         path: solidity-mocha-test-report.json # Path to test results
@@ -77,9 +78,10 @@ jobs:
       run: npm run test:ethereum-mainnet
       env:
         ETHEREUM_NODE_URL: ${{ secrets.ETHEREUM_NODE_URL }}
+
     - name: Ethereum mainnet Test Report
       uses: dorny/test-reporter@v1
-      if: success() || failure()              # run this step even if previous step failed
+      if: ${{ !env.ACT }} && (success() || failure())              # run this step even if previous step failed
       with:
         name: Ethereum mainnet Tests          # Name of the check run which will be created
         path: ethereum-mainnet-mocha-test-report.json # Path to test results
