hardhat-mangrove: Add build and deps to CI

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -83,6 +83,7 @@ jobs:
       with:
         name: commonlib-out.zip
         path: commonlib-out.zip
+  # ==== End job: commonlib-js ====
 
   # ==== Job: Build and test Mangrove Core
   mangrove-solidity:
@@ -231,18 +232,18 @@ jobs:
 
   # ==== End job mangrove-solidity-doc ====
 
-  # ==== Job: Build and test mangrove.js ====
-  mangrove-js:
+  # ==== Job: Build and test hardhat-mangrove ====
+  hardhat-mangrove:
     needs: mangrove-solidity
 
     runs-on: ubuntu-latest
 
     env:
-      working-directory: packages/mangrove.js
+      working-directory: packages/hardhat-mangrove
 
     defaults:
       run:
-        working-directory: packages/mangrove.js
+        working-directory: packages/hardhat-mangrove
 
     strategy:
       matrix:
@@ -284,6 +285,104 @@ jobs:
       with:
         args: unzip -qq mangrove-solidity-out.zip
 
+    # build
+    - name: hardhat-mangrove - Build
+      run: yarn run build-this-package
+
+    - name: Save status of build
+      run: echo "hardhat_mangrove_built=true" >> $GITHUB_ENV    
+
+    # == run and report tests == 
+    # NOTE: Uncomment the following two steps, when hardhat-mangrove has tests -->
+    # - name: hardhat-mangrove - Tests
+    #   run: yarn run test
+
+    # - name: hardhat-mangrove - Test Report
+    #   uses: dorny/test-reporter@v1
+    #   if: ${{ env.hardhat_mangrove_built && (success() || failure()) }}
+    #   with:
+    #     name: hardhat-mangrove - Tests                   # Name of the check run which will be created
+    #     path: packages/hardhat-mangrove/integration-tests-report.json # Path to test results
+    #     reporter: mocha-json                               # Format of test results
+
+    # save artifacts for later stages
+    # NOTE: Uncomment the following two steps, if/when hardhat-mangrove has build artefacts -->
+    # - name: Zip output
+    #   uses: montudor/action-zip@v1
+    #   with: 
+    #     args: zip -qq -r hardhat-mangrove-out.zip ${{env.working-directory}}/dist
+
+    # - name: Cache hardhat-mangrove output as artifact
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: hardhat-mangrove-out.zip
+    #     path: hardhat-mangrove-out.zip
+  # ==== End job: hardhat-mangrove ====
+
+  # ==== Job: Build and test mangrove.js ====
+  mangrove-js:
+    needs: [mangrove-solidity, hardhat-mangrove]
+
+    runs-on: ubuntu-latest
+
+    env:
+      working-directory: packages/mangrove.js
+
+    defaults:
+      run:
+        working-directory: packages/mangrove.js
+
+    strategy:
+      matrix:
+        node-version: [14.x]
+
+    steps:
+
+    # == Git checkout ==
+    - name: Checkout
+      uses: actions/checkout@v2
+      # Workaround for https://github.com/npm/cli/issues/2610
+      with:
+        persist-credentials: false
+
+    - name: Reconfigure git to use HTTP authentication
+      # Workaround for https://github.com/npm/cli/issues/2610    
+      run: >
+        git config --global url."https://github.com/".insteadOf
+        ssh://git@github.com/
+
+    # == yarn setup ==
+    - name: Yarn setup (caching yarn dependencies)
+      uses: actions/setup-node@v2
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'yarn'
+        
+    - run: yarn install --immutable
+      working-directory: . # Yarn must run in root to ensure monorepo setup
+
+    # == download and unzip artefacts ==
+    - name: Download cached mangrove-solidity artifact
+      uses: actions/download-artifact@v2
+      with:
+        name: mangrove-solidity-out.zip
+
+    - name: Unzip mangrove-solidity artifact
+      uses: montudor/action-zip@v1
+      with:
+        args: unzip -qq mangrove-solidity-out.zip
+
+    # NOTE: Uncomment the following two steps, if/when hardhat-mangrove has build artefacts -->
+    # - name: Download cached hardhat-mangrove artifact
+    #   uses: actions/download-artifact@v2
+    #   with:
+    #     name: hardhat-mangrove-out.zip
+
+    # - name: Unzip hardhat-mangrove artifact
+    #   uses: montudor/action-zip@v1
+    #   with:
+    #     args: unzip -qq hardhat-mangrove-out.zip
+
     # == build == 
     - name: Mangrove.js build
       run: yarn run build-this-package
@@ -319,7 +418,7 @@ jobs:
         
   # ==== Job: Build and test cleaning-bot ====
   cleaning-bot:
-    needs: [commonlib-js, mangrove-js]
+    needs: [commonlib-js, mangrove-solidity, hardhat-mangrove, mangrove-js]
 
     runs-on: ubuntu-latest
 
@@ -365,10 +464,21 @@ jobs:
       with:
         name: mangrove-solidity-out.zip
 
-    - name: Unzip artifact
+    - name: Unzip mangrove-solidity artifact
       uses: montudor/action-zip@v1
       with:
         args: unzip -qq mangrove-solidity-out.zip
+
+    # NOTE: Uncomment the following two steps, if/when hardhat-mangrove has build artefacts -->
+    # - name: Download cached hardhat-mangrove artifact
+    #   uses: actions/download-artifact@v2
+    #   with:
+    #     name: hardhat-mangrove-out.zip
+
+    # - name: Unzip hardhat-mangrove artifact
+    #   uses: montudor/action-zip@v1
+    #   with:
+    #     args: unzip -qq hardhat-mangrove-out.zip
 
     - name: Download cached mangrove.js artifact
       uses: actions/download-artifact@v2
