Move Mocha configuration to config file

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -19,7 +19,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [12.x, 14.x, 16.x]
+        node-version: [16.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
@@ -41,16 +41,18 @@ jobs:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
     - run: npm ci
-    - run: npm run build --if-present
 
-    - run: npm run test
-    - name: Test Report
+    - name: Solidity Compile
+      run: npx hardhat compile
+    - name: Solidity Tests
+      run: npx hardhat test-solidity --no-compile
+    - name: Solidity Test Report
       uses: dorny/test-reporter@v1
-      if: success() || failure()     # run this step even if previous step failed
+      if: success() || failure()              # run this step even if previous step failed
       with:
-        name: JEST Tests             # Name of the check run which will be created
-        path: mocha-test-report.json # Path to test results
-        reporter: mocha-json         # Format of test results
+        name: Solidity Tests                  # Name of the check run which will be created
+        path: solidity-mocha-test-report.json # Path to test results
+        reporter: mocha-json                  # Format of test results
 
     - run: npm run doc
 
